#ifndef FD_SNOWFLAKE_H
#define FD_SNOWFLAKE_H

#define FD_SNOWFLAKE_PIN_LED_POWER 8
#define FD_SNOWFLAKE_PIN_LED_DIN 11

#define FD_SNOWFLAKE_PIN_BATTERY_SENSE 24
#define FD_SNOWFLAKE_PIN_BATTERY_DIV_2 1
#define FD_SNOWFLAKE_PIN_USB_POWERED 27
#define FD_SNOWFLAKE_PIN_CHARGE_STATUS 26
#define FD_SNOWFLAKE_PIN_CHARGE_CURRENT 2

#endif